# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 8
mac: "tar_comm_mac"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent: "rnn" # Default rnn agent
agent_output_type: "q"
learner: "cate_q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32

name: "tar_qmix_smac_parallel"

atom: 51
vmin: -10
vmax: 10

# Comm
comm: True
comm_embed_dim: 10
comm_method: "tar"
# c_beta: 1.
# comm_beta: 0.001
# comm_entropy_beta: 1e-6
# gate_loss_beta: 0.00001
only_downstream: True
use_IB: False
# is_print: False

# is_comm_beta_decay: False
# comm_beta_start_decay: 20000000
# comm_beta_target: 1e-2
# comm_beta_end_decay: 50000000

# is_comm_entropy_beta_decay: False
# comm_entropy_beta_start_decay: 20000000
# comm_entropy_beta_target: 1e-4
# comm_entropy_beta_end_decay: 50000000

signature_dim: 32

is_cur_mu: False
test_is_cut: False
test_is_cut_prob: False
test_cut_prob_thres: 0.
test_cut_prob_list: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
test_cut_list: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
test_is_print_once: False
