env: tracker1

env_args:
  difficulty: "7"
  obs_instead_of_state: False
  obs_last_action: False
  obs_pathing_grid: False
  obs_terrain_height: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  partial_obs: True
  debug: False
  is_print: False
  print_rew: False
  print_steps: 1000

learner_log_interval: 100000
log_interval: 100000
runner_log_interval: 100000
t_max: 10050000
test_interval: 10000
test_nepisode: 300
test_greedy: True